name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build e Testes (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências
        run: mvn install

      - name: Rodar testes
        run: mvn test

  deploy:
    name: Deploy para Produção (CD)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy PRD
        run: |
          echo "Deploy em produção realizado com sucesso."
